### ISSUE TITLE
Re-using the cURL handle breaks all but the first request

### ISSUE THREAD

**Issue by xrstf** [fruux/sabre-http#35] opened 2014-11-12 12:04 UTC
I am using SabreDAV 2.0.5 with Sabre HTTP 2.0.4 on PHP 5.6 (Win x64). This is my test code, which should just check if a file exists (expected to 404) and then create it:

```php

require 'vendor/autoload.php';

$client = new Sabre\DAV\Client(array(
    'baseUri' => 'http://my.webdav.host/',
    'proxy'   => 'http://127.0.0.1:8888/'   // for debugging with Fiddler
));

$client->request('HEAD', '/foo.txt'); // throws NotFound exception, as expected
$client->request('PUT', '/foo.txt', 'my content');
```

We are -- for testing -- tunneling WebDAV through nginx. Unexpectedly, we get an HTTP 500 for the PUT request, because it looks like this in Fiddler

```
PUT http://my.webdav.host/foo.txt HTTP/1.1
Host: my.webdav.host
Accept: */*
Connection: Keep-Alive

```

There is no content and no ``Content-Length`` header, making the nginx barf.

I traced the problem down to the ``Sabre\HTTP\Client`` class and its recycling of the cURL handle.

```php
protected function doRequest(RequestInterface $request) {

    $settings = $this->createCurlSettingsArray($request);

    if (!$this->curlHandle) {
        $this->curlHandle = curl_init();
    }

    // ...snip...
}
```

If I disable the ``if`` and always recreate a new cURL handle, everything works as expected.

Since the ``curlHandle`` is private, I have very little chance to work around this except creating a new SabreDAV client for every single request.

**Comment by Hywan** [comment] 2015-01-12 13:10
@xrstf If you add the `CURLOPT_FORBID_REUSE` or `CURLOPT_FRESH_CONNECT` constants, does it solve your issue?

**Comment by evert** [comment] 2015-01-12 15:10
@Hywan even if that solved his issue, I think the most important thing is that we attempt to reproduce this and figure out why it's happening in the first place. On my machine, this is definitely not a problem...

**Comment by Hywan** [comment] 2015-01-12 15:16
@evert I am not able to reproduce the bug neither, that's why I was asking @xrstf to see if these options should solve the problem at first. If no, I will dig deeper.

**Comment by andreaswolf** [comment] 2015-05-17 15:52
I can reproduce this with 4.0.0-alpha1. It is fixed on most recent master, but sabre/dav still uses 4.0.0-alpha1. Adding the following to `composer.json` updates `sabre/http` to master instead:

```json
"require": {
  "sabre/http": "dev-master as 4.0.0-alpha1"
}
```

I’m using PHP 5.5.24 on Fedora 20 (cURL 7.32.0). As some people reported not being able to reproduce this: If you have anything I can do to help testing this, just contact me (here or via mail).

**Comment by evert** [comment] 2015-05-18 05:43
Hi Andreas,

I'm releasing 4.0.0-alpha2 right now to solve this.

**Comment by evert** [comment] 2015-05-18 05:45
Oh my I never realized this was the same ticket as #47  :(

On the bright side, the unittests are now changed to catch issues similar to this. I'm very sorry you had to wait this long.

**Comment by evert** [comment] 2015-05-18 07:06
Just released the second alpha

**Closed** 2015-05-19 09:16 UTC
Labels: bug
